### ISSUE TITLE
Publish staff site through github actions

### ISSUE THREAD

**Issue by andrewpbray** [stat20/course-materials#418]
Create new `publish-staff-site.yml` that

1. on PR to main
2. starts up stat20 image
3. runs pre-render scripts (propagate-dates and write-toc)
4. renders / publishes website to [stat20staff](https://stat20guide.netlify.app/)

@ryanlovett could you help me get this file right? I'm not sure how to do 2  and i'm not sure what the best approach is for 4 given that we'll be needing to pass permissions. The options for 4 as I see it are:

a. Use the official quarto publish action
b. Run `quarto publish --other options` manually
b. Wrap 4 into a single R script that could also contain 3 (as an example, see `render-live.r` for a script that does a partial render correctly when working locally).

**Comment by ryanlovett** [comment]
Regarding 1-3, it is possible to run an action from [within a Docker container](https://github.com/addnab/docker-run-action). It could be something like:

```yaml
jobs:
  publish:
    name: publish to stat20staff netlify
    runs-on: ubuntu-latest
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v2
      # run the container, attaching this repo as a working directory
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: stat20/stat20-docker:latest
          options: -v ${{ github.workspace }}:/home/rstudio/stat20
          shell: bash
          run: |
            /path/to/propagate-dates
            /path/to/write-toc
            quarto publish --other options
```

I think that your b#2 (single script) might make things easier.

If you're using netlify, then the publish command would presumably need access to credentials which could be repo secrets.

I can explore this if you'd like, though I wouldn't want to publish to anywhere important. Is there a way of specifying options so that the materials are published to a staging site?
