### ISSUE TITLE
Create slide classes

### ISSUE THREAD

**Issue by andrewpbray** [stat20/course-materials#6]
For activity slides, set attributes via syntax like

```markdown
## Activity 1 {class="activity"}
```

which would correspond to a class rule

```css
.activity {
  background-color: $blue;
}
```

### Class ideas
1. .activity: background color
2. .poll-results: center iframe and add data-menu-title
